export const leaderEffects = {
  'stars-chris-redfield': { type: 'boost-lowest-row', amount: 3 },
  'stars-jill-valentine': { type: 'boost-lowest-row', amount: 2 },
  'stars-wesker-captain': { type: 'boost-lowest-row', amount: 2 },
  'rpd-leon-kennedy': { type: 'boost-lowest-row', amount: 2 },
  'dso-leon-kennedy-requiem': { type: 'boost-lowest-row', amount: 2 },
  'fbi-leon-kennedy-re4': { type: 'cleanse-allies' },
  'bsaa-chris-redfield': { type: 'boost-if-opponent-bow', amount: 2 },
  'bsaa-jill-valentine': { type: 'boost-lowest-row', amount: 2 },
  'umbrella-william-birkin-human': { type: 'deploy-ally', cardId: 'umbrella-birkin-g-type', row: 'Melee', count: 1 },
  'umbrella-wesker': { type: 'weaken-highest-opponent-row', amount: 2 },
  'umbrella-hunk': { type: 'deploy-ally', cardId: 'umbrella-uss-alpha-team', row: 'Ranged', count: 1, presenceBonus: { cardId: 'umbrella-hunk-unit', extra: 1 } },
  'illuminados-saddler': { type: 'weaken-highest-opponent-row', amount: 2 },
  'illuminados-krauser': { type: 'boost-highest-row', amount: 3 },
  'illuminados-salazar': { type: 'weaken-highest-opponent-row', amount: 3 },
  'connections-eveline': { type: 'weaken-highest-opponent-row', amount: 2 },
  'connections-mother-miranda-leader': { type: 'boost-highest-row', amount: 3 },
  'connections-victor-gideon': { type: 'advance-trigger-evolutions' },
}
